### set baseUrl=http://localhost:3000

### load all posts
GET http://localhost:3000/posts
###

### Create a new post
POST http://localhost:3000/posts
Content-Type: application/json

{
  "title": "My second Post",
  "content": "This is the content of my second post.",
  "authorId": 5
}
###