@baseUrl=localhost:3000

### load all users
GET {{baseUrl}}/users
###

### get one user
GET {{baseUrl}}/users/1
###

### Creates a new user
POST {{baseUrl}}/users
Content-Type: application/json

{
  "login": "j.doe",
  "firstName": "J.",
  "lastName": "DOE",
  "email": "123"
}
###